# Generated by Django 4.2.9 on 2024-02-07 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 9, 19, 50, 42, 374919, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
