# Generated by Django 4.2.9 on 2024-02-15 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 17, 18, 33, 19, 902453, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
